### ISSUE TITLE
Atom feed in Newsboat

### ISSUE THREAD

**Issue by rwmpelstilzchen** [ohare93/ohare93.github.io#19]
Hi,

Thanks for making the Ultimate Geography deck and your blog :-)

When I subscribe to your blog with [Newsboat](https://newsboat.org/) using [Atom](https://ohare.blog/feed.xml), I get post URLs like `https://ohare.blog/ohare.blog/ohare.blog/anki-beginner-steps`. I guess this is because you use `ohare.blog` instead of `https://ohare.blog`, which gets interpreted as relative.

Júda

**Comment by jeprecated** [comment]
Hey. I am greatly surprised anyone knows about my blog 😅  not that I post often at all. But thanks!

Most importantly: I did not make the Ultimate Geography deck, I merely help maintain it somewhat.

As to your question, I have no bloody clue why it does that 🤔  seems weird, indeed!

**Comment by Minoru** [comment]
That's right, all the URLs in the feed are treated as relative because they lack the protocol. I think this

https://github.com/ohare93/ohare93.github.io/blob/bb767c02cc11affc5797a86097208f282cd2729a/_config.yml#L21

has to say "<b>https://</b>ohare.blog".

You'll know the issue is fixed when this:

```xml
<link href="ohare.blog/moving-to-denmark" rel="alternate" type="text/html" title="Moving to Denmark" />
```

turns into this:

```xml
<link href="https://ohare.blog/moving-to-denmark" rel="alternate" type="text/html" title="Moving to Denmark" />
```

**Comment by jeprecated** [comment]
Alright that seems to have fixed it :+1: Confirmed? :grin:
